# -*- coding: utf-8 -*-
"""Exercises on Algebra Data Structures

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m45BIiK-q3-R_HQQ389eG9yjsOmmmJJp

**SOAL NO 1 (Exercises on Algebra Data Structures)**
"""

# selesaikan soal berikut
# What is the transpose of this vector?
# [25]
# [2]
# [-3]
# [-23]
import numpy as np

x = np.array([[25],
      [2],
      [-3],
      [-23]])
x

x_t = x.T
x_t