# -*- coding: utf-8 -*-
"""Matrix Tensors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Owj2xERVVFTw8Cwpd314GYVUoM88qf5a

**SOAL NO 1 (Matrix Tensors)**
"""

import numpy as np

# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[15, 7, 20], [10, 6, 4]])
X

# tampilkan ukuran dari matrix X
X.shape

# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

"""**SOAL NO 2 (Matrix Tensors) (PyTorch)**"""

# ulangi soal nomor 1 menggunakan pytorch
import torch

X_pt = torch.tensor([[15, 7, 20], [10, 6, 4]])
X_pt

X_pt.shape

X_pt[:,0]

X_pt[1,:]

# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

X_tf = tf.Variable([[15, 7, 20], [10, 6, 4]])
X_tf

tf.shape(X_tf)

X_tf[:,0]

X_tf[1,:]