# -*- coding: utf-8 -*-
"""Norms and Unit Vectors

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAdtWjNN5qvlpgZa70e1j9QW6Nu9E7Wb

**SOAL NO 1 (Norms and Unit Vectors)**
"""

import numpy as np

# buat vector x dengan ukuran 3x1
x = np.array([[15],
              [7],
              [31]])
x

# hitung nilai L2 norm dari vector x
(15**2 + 7**2 + 31**2)**(1/2)

"""**SOAL NO 2 (Norms and Unit Vectors)**"""

# buat vector v dengan elemen (3,4)
v = np.array([3, 4])
print(f'Vektor asli: {v}')

# hitung nilai L2 norm dari vector v
norm = np.linalg.norm(v)
print(f'Panjang vektor: {norm}')

# tampilkan unit vector dari vector v
unit_v = v / norm
print(f'Unit vektor: {unit_v}')

# hitung panjang unit vector dari vector v
print(f'Panjang unit vektor: {np.linalg.norm(unit_v)}')