# -*- coding: utf-8 -*-
"""scalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KmZMHBhgyfpJvtgX6sHRQuuaJq8qtk52

**SOAL NO 1 (SCALAR)**
"""

# buat variabel skalar x dan simpan suatu nilai skalar
x = 25

# tampilkan tipe data dari x
type(x)

# buat variabel skalar y dan simpan suatu nilai skalar
y = 50

# tampilkan tipe data dari y
type(y)

# jumlahkan x+y
penjumlahan = x + y
print(penjumlahan)

# buat variabel bernama x_float dan simpan suatu nilai desimal
x_float = 3.90

# jumlahkan x_float dengan y
penjumlahan2 = x_float + y
print(penjumlahan2)

# tampilkan tipe data dari x_float
type(x_float)

"""**SOAL NO 2 (SCALAR) (TENSORFLOW)**"""

# lakukan tahapan pada soal 1 dengan menggunakan tensorflow
import tensorflow as tf

x_tf = tf.Variable(25)

# tampilkan tipe data dari x_tf (Tensorflow)
print(f'Type dari x_tf adalah: {type(x_tf)}')

# buat variabel skalar y_tf dan simpan suatu nilai skalar (Tensorflow)
y_tf = tf.Variable(50)

# tampilkan tipe data dari y_tf (Tensorflow)
print(f'Type dari y_tf adalah: {type(y_tf)}')

# jumlahkan x_tf + y_tf (Tensorflow)
penjumlahan3 = x_tf + y_tf
print(penjumlahan3)

# buat variabel bernama x_float_tf dan simpan suatu nilai desimal (Tensorflow)
x_float_tf = tf.Variable(3.90)

# jumlahkan x_float_tf dengan y_tf (Tensorflow)
y_float_tf = float(y_tf)
penjumlahan4 = x_float_tf + y_float_tf
print(penjumlahan4)

# tampilkan tipe data dari x_float_tf (Tensorflow)
print(f'Type dari x_float_tf adalah: {type(x_float_tf)}')

"""**SOAL NO 3 (SCALAR) (PYTORCH)**"""

# lakukan tahapan pada soal 1 dengan menggunakan pytorch
import torch

x_pt = torch.tensor(25)

# tampilkan tipe data dari x_pt (PyTorch)
print(f'Type dari x_pt adalah: {type(x_pt)} dengan nilai {x_pt}')

y_pt = torch.tensor(50)

print(f'Type dari y_pt adalah: {type(y_pt)} dengan nilai {y_pt}')

penjumlahan5 = x_pt + y_pt
print(penjumlahan5)

x_float_pt = torch.tensor(3.90)

penjumlahan6 = x_float_pt + y_pt
print(penjumlahan6)

print(f'Type dari x_float_pt adalah: {type(x_float_pt)} dengan nilai {x_float_pt}')