# -*- coding: utf-8 -*-
"""Vectors and Vector Transposition

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHXbh7mHhZSFq2fhR_rx3idN6Tvoscpi

**SOAL NO 1 (VECTORS AND VECTOR TRANSPOSITION)**
"""

# buat vector x dengan ukuran 3x1
import numpy as np

x = np.array([[10],
              [15],
              [20]])
x

# hitung panjang vector x
len(x)

# tampilkan ukuran vector x
x.shape

# tampilkan tipe data dari vector x
type(x)

# akses elemen pertama dari vector x
x[0]

# tampilkan tipe data elemen pertama dari vector x
type(x[0])

"""**SOAL NO 2 (VECTORS AND VECTOR TRANSPOSITION)**"""

# lakukan transpose pada vector x dan simpan pada variabel x_t
x_trans = x.T
x_trans

# tampilkan ukuran dari vector x_t
x_trans.shape

# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[10],
              [15],
              [20]])
y

# tampilkan ukuran dari vector x_t
y.shape

"""**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (TENSORFLOW)**"""

# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import tensorflow as tf

x_tf = tf.Variable([[10],
                    [15],
                    [20]])
x_tf

x_tf.shape

y_tf = tf.Variable([[10],
                    [15],
                    [20]])
y_tf

y_tf.shape

"""**SOAL NO 3 (VECTORS AND VECTOR TRANSPOSITION) (PYTORCH)**"""

# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch

x_pt = torch.tensor([[10],
                    [15],
                    [20]])
x_pt

x_pt.shape

y_pt = torch.tensor([[10],
                    [15],
                    [20]])
y_pt

y_pt.shape